### ISSUE TITLE
Snow Backrounds on Long Idle

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#10]
We must change the pictures. We don't have snow-days anymore
Who is in charge for that?

**Comment by ChrisMoraitisrnd3** [comment]
@dtsanakas

**Comment by ChrisMoraitisrnd3** [comment]
@dtsanakas  Please make a collection of images you like (such as the artwork we have at "Check for updates" panel) because we should change the current images on Long Idle.

**Comment by dtsanakas** [comment]
@ChrisMoraitisrnd3 @outcast1000 
ok! 
**Abstract collection // 15 images**

**Comment by ChrisMoraitisrnd3** [comment]
οκ, v3.11
