### ISSUE TITLE
Debug Panel / Experimental Value loose value

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#11]
The exper toggle never stays!

**Comment by ChrisMoraitisrnd3** [comment]
The hidden settings bar is beneath the Debug Panel

**Comment by gvergidis** [comment]
Οκ διορθώθηκε.

**Comment by ChrisMoraitisrnd3** [comment]
Και το διπλό Reset Setup?

**Comment by gvergidis** [comment]
Έχει διορθωθεί και αυτό :) Όπως επίσης και το debug panel πήγε πίσω από το settings bar (μπάρα πάνω).

**Comment by ChrisMoraitisrnd3** [comment]
η μπάρα πάλι πάνω είναι πάλι πίσω από debug....αλλά η τιμή μένει οπότε το κλείνω
