### ISSUE TITLE
Power Button is enabled inside Settings / Setup Wizard and it send MAIC to Long Idle

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#12]
The power button (mute) works when I am on "Checks for updates" panel
So, it redirects me to Front Panel of 3D model

**Comment by outcast1000** [comment]
A common user would never get into this. In any case we must check it.

**Comment by outcast1000** [comment]
Also. Does this work while in Settings?

**Comment by ChrisMoraitisrnd3** [comment]
Yes. still exists v3.03

**Comment by ChrisMoraitisrnd3** [comment]
v 3.09 --> ok
