### ISSUE TITLE
Updater - Download progress icon on Idle screen

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#24]
We should present the updating - downloading progress

**Comment by gvergidis** [comment]
Εννοείτε κάτω δεξιά που δείχνει τα βελάκια; Αρχικά, αυτά δεν υποτίθεται θα τα αλλάζαμε; Ας κάνει ο @dtsanakas ένα gif με ένα loading που περιστρέφεται (να έχει background στρόγγυλο Δημήτρη) και ας γράφουμε εκεί μέσα το progress.

**Comment by dtsanakas** [comment]
@gvergidis ελα να το κανουμε σωστα!

**Comment by outcast1000** [comment]
O @jimarab είπε ότι ο gif player έχει πρόβήμα.

**Comment by gvergidis** [comment]
Έβγαλα το gif και στην θέση του έβαλα ένα interactive image. Επίσης, όπως είπαμε, ο gif player δεν έχει πρόβλημα. Ο @jimarab είχε ζητήσει, για να μειώσουμε το load στην αρχή, να μην φορτώνουν οι gif εικόνες στο onStart αλλά στο 2ο onEnable και αυτό έκανα. Ο controller κανονικά ξεκινάει cacha ροτνας όλα τα frames της εικόνας για να είναι πιο smooth η αναπαραγωγή. Αυτό δυστυχώς θέλεί λίγη cpu. Την επόμενη φορά θα γράφω στο changelog ποιος μου ζήτησε τι και τι έκανα γι αυτό.

**Comment by outcast1000** [comment]
@ChrisMoraitisrnd3 Θα κλείσει αυτο?

**Comment by ChrisMoraitisrnd3** [comment]
@jimarab @outcast1000  Στην 3.05 που είχαμε έξω δεν φαίνεται το progress. Στις άλλες πειραματικές που είχα μετέπειτα φάνηκε ο κύκλος που γεμίζει με μπλε. Ξεκινάει και είναι 100% για 2-3 δευτερόλεπτα και μετά πάει στο 0% φθάνει 99% και έκλεισε να ξαναφορτώσει  --> v3.09

**Comment by gvergidis** [comment]
@jimarab βάλε τον controller σαν default να ξεκινάει από το 0 και είναι οκ.

**Comment by outcast1000** [comment]
Τελικά δε θα μπεί τίποτα. Το κλείνω
