### ISSUE TITLE
Youtube - Volume may become low

### ISSUE THREAD

**Issue by outcast1000** [ChrisMoraitisrnd3/MAIC-Issues#25]
JKAM reported that some tracks may be played lowed than normal on >2.71 on certain cases. Lets see if the volume control has any issues

**Comment by gvergidis** [comment]
Ο player ήταν στο 80% αλλά δεν νομίζω να επηρεάζει τόσο. Θα το κοιτάξω ξανά αύριο.

**Comment by outcast1000** [comment]
Ισως όταν ανεβακατεβάζεις την ένταση (πχ για να μιλήσει η MAIC) να συμβαίνει κάτι

**Comment by gvergidis** [comment]
Αυξήθηκε η ένταση του player κατά 5 dbs. Θα είναι στην επόμενη version. Ας δοκιμαστεί τότε.

**Comment by outcast1000** [comment]
O JKam έγραψε "Με αρκετα μεγαλη βεβαιοτητα εχουμε χαμηλωσει την ενταση του youtube. Δευτερα το φτιαχνουμε"
@gvergidis το ειχες κατεβάσει γενικά ή κατεβαίνει κάποια στιγμή από τα πάνω κάτω? Επιπλέον τι άλλο περιθώριο εχουμε όσο αναφορά την ένταση;

**Comment by gvergidis** [comment]
@outcast1000 Δεν το έχω κατεβάσει. Είναι το φίλτρο που είναι για το μπάσο και το tremble. Έπαιρνε λάθος default τιμές. Τώρα είναι οκ.

**Comment by outcast1000** [comment]
@ChrisMoraitisrnd3 OK αυτό? Αν ναι ας κλείσει

**Comment by ChrisMoraitisrnd3** [comment]
v3.08 -> ok bass & trble 75%
