### ISSUE TITLE
TTS - Νεράιδα / Φιλί

### ISSUE THREAD

**Issue by outcast1000** [ChrisMoraitisrnd3/MAIC-Issues#26]
Σενάριο αναπαραγωγής:
1. Επιλέγουμε νεράιδα
2. Λέμε "Τι κάνεις" -> TTS δουλεύει
3. Την κάνουμε να δώσει ένα φιλί
4. Λέμε "Τι καιρό κάνεις" (βασικά οτιδήποτε) και το TTS δε δουλεύει

**Comment by ChrisMoraitisrnd3** [comment]
Όχι μια χαρά είναι. τι εννοείς?

**Comment by ChrisMoraitisrnd3** [comment]
@mariamls  ? μια χαρά παίζει

**Comment by mariamls** [comment]
Mετά το χόρεψε ζήτα να σου δώσει ένα φιλί. Τότε οτιδήποτε και αν ζητήσεις μετά πχ καιρός , wiki κτλ δεν έχει tts

**Comment by mariamls** [comment]
Αν στη συνέχεια επιλέξεις την προσωπικότητα Ελληνικά Γυναίκα συνεχίζει να μην υπάρχει tts σε καιρό, wiki κτλ.. Χρειάζεται επαννεκίνηση. @ChrisMoraitisrnd3

**Comment by ChrisMoraitisrnd3** [comment]
@outcast1000 @jimarab @mariamls 
 πρέπει να ξανα ελέγξουμε τις εντολές του Αντρέα για τα avatar.
Δε γνωρίζω ακριβώς ποιές είναι

**Comment by ChrisMoraitisrnd3** [comment]
@mariamls  ότι εντολές έχετε προτείνω να τα γράψουμε στο wiki εδώ
@outcast1000  τι λες?

**Comment by mariamls** [comment]
Στις δοκιμές που έκανα παρατήρησα πως το πρόβλημα είναι στη νεράιδα /φιλί @ChrisMoraitisrnd3 @outcast1000 
Αναλυτικά
1. επιλέγουμε νεράιδα
2. χόρεψε
3. καιρός/wiki  To tts δουλεύει

Αν όμως 
1. επιλέγουμε νεράιδα
2. φιλί
3.καιρός/wiki το tts χάνεται
4. επιλέγουμε Ελληνικά Γυναίκα
5. οτιδήποτε ρωτήσουμε δε δουλέυει το tts

**Comment by mariamls** [comment]
Μόλις είδα πως το tts επανέρχεται σε γυναίκα και νεράιδα αν ζητήσεις ένα φιλί  αντί για επανεκκίνηση.
@ChrisMoraitisrnd3 @outcast1000

**Comment by mariamls** [comment]
Συμβαίνει το εξής :  Η προσωπικότητα νεράιδα που υποτίθεται οτι είναι στο public εμφανίζονται τα log στο dev @ChrisMoraitisrnd3 @outcast1000

**Comment by mariamls** [comment]
Ουσιαστικά η νεράιδα που νομίζαμε ότι είναι στο public έπαιρνε τις απαντήσεις απο το dev

**Comment by outcast1000** [comment]
@mariamls @ChrisMoraitisrnd3 . Τελίκά με το φιλί τι γίνεται? Εχω μείνει ότι σκάει με Ανδρα & Νεράιδα αλλά όχι με γυναίκα. Είναι έτσι?

**Comment by mariamls** [comment]
@outcast1000 @ChrisMoraitisrnd3 Δεν σκάει σε καμία προσωπικότητα.

**Comment by ChrisMoraitisrnd3** [comment]
Ο Αντρέας είχε βάλει "δώσε φιλι πριν και ...μετά" -> το αποτέλεσμα είναι να πηγαίνει αρχική και να λέει "Σμουτς" - >σωστά? 
Τότε είμαστε οκ στην 3.09

**Comment by mariamls** [comment]
Αυτό ακριβώς κάνει στην 09. Επιστρέφει στην αρχική οθόνη και λέει Σμουτσ εκτός απο τη γυναίκα που κάνει και την κίνηση.
