### ISSUE TITLE
Radio - Favourite stations - Images

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#27]
έχω βάλει δύο σταθμούς στα αγαπημένα. όταν τα ανοίξω εμφανίζεται μόνο ο πρώτος χωρίς εικόνα (με την default) και όσες φορές πατήσω επόμενο δεν αλλάζει ούτε βάζει εικόνα.
Υπάρχει όμως ο δεύτερος στη λίστα όταν την ανοίγω

**Comment by gvergidis** [comment]
Έχει διορθωθεί από την Παρασκευή. Στην νέα έκδοση θα είναι περασμένο.
https://changelog.vergidis.com/version-3.05

**Comment by outcast1000** [comment]
@ChrisMoraitisrnd3  Θα κλείσει αυτό?

**Comment by ChrisMoraitisrnd3** [comment]
v3.09 -> ok (εάν ο σταθμός δεν έχει εικόνα έχουμε την default -μαύρο με κόκκινο σηματάκι)
