### ISSUE TITLE
3rd party apps (Spotify - Skype- Netflix)

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#32]
Με το που κατέβασα την 3.09 έπαιξα λίγο στο youtube και μπήκα Spotify. Έπαιξε ένα τραγούδι, σταματάω, γυρνάω και βγαίνω με το back
Και αμέσως έσκασε! Restart η maic

**Comment by outcast1000** [comment]
Εσκασε ή απλά έκανε restart? Αν είναι το 2ο τότε είναι (δυστυχώς) φυσιολογικό. Αν στο μέλλον γίνει πιο ελαφρια η MAIC ίσως διορθωθεί

**Comment by ChrisMoraitisrnd3** [comment]
Ποιά η διαφορά? Εμφανίζεται μαύρη εικόνα για λίγο και μετά η maic με τα ακουστικά κι φορτώνει....από την παραπάνω περιγραφή μου ήθελα να πω πως δεν την είχα χρησιμοποιήσει πολύ ούτε την είχα ώρα ανοιχτή.

**Comment by outcast1000** [comment]
Η διαφορά είναι ότι αν (1) σκάει βγάζει ένα μήνυμα ότι έσκασε => έχει πρόβλημα ο κώδικας => Θα πρέπει να το φτιάξουμε. Αν όμως απλά κάνει restart (2) αυτό οφείλεται ότι το Android θεώρησε ότι τελείωσε η μνήμη του => έκλεισε την εφαρμογή μας => Δεν μπορούμε να κάνουμε κάτι
Μάλλον ήταν το #2. Προτείνω να το κλείσουμε επειδή δεν έχουμε τρόπο να το αντιμετωπίσουμε..

**Comment by ChrisMoraitisrnd3** [comment]
οκ το κλείνω
