### ISSUE TITLE
Youtube @commands-restart is not working 

### ISSUE THREAD

**Issue by mariamls** [ChrisMoraitisrnd3/MAIC-Issues#33]
Αν ζητήσεις "κάνε επανάληψη το βίντεο" στο youtube δεν κάνει @^@commands-restart αλλά πηγαίνει σε άκυρο βίντεο με τίτλο επανάληψη.

**Comment by outcast1000** [comment]
@gvergidis νομίζω ότι κάτι ξέφυγε εκεί.

**Comment by gvergidis** [comment]
Το έφταιξα. Είχα βάλει stop και play αλλά τελικά το seek είναι καλύτερο. Θα βγει στην επόμενη έκδοση.

**Comment by ChrisMoraitisrnd3** [comment]
v3.11-> με σκέτο επανάληψη δεν είναι η εντολή? εάν πεις "επανάληψη" λειτουργεί σωστά

**Comment by gvergidis** [comment]
Νομίζω ναι. Δεν ξέρω τι γκάμα έχουν βάλει τα κορίτσια στα διαλογικά.

**Comment by ChrisMoraitisrnd3** [comment]
οκ 3.15
