### ISSUE TITLE
Mini Maic / Dance (v3.09)

### ISSUE THREAD

**Issue by mariamls** [ChrisMoraitisrnd3/MAIC-Issues#37]
Στη mini maic η νεράιδα δεν χορεύει. Η γυναίκα κανονικά.

**Comment by outcast1000** [comment]
@mariamls Κανονικά δεν πρέπει να έχει διαφορά ανάμεσα στη μεγάλη και στη μικρή MAIC . Μπορείς να μας δώσεις βήματα αναπαραγωγής?

**Comment by mariamls** [comment]
1. mini maic/ νεράιδα
2. χόρεψε
3. Παραμένει στην αρχική οθόνη/ επιστρέφει στην αρχική οθόνη αν βρισκόταν αλλού.

**Comment by outcast1000** [comment]
Duplicate of #30

**Comment by outcast1000** [comment]
@ChrisMoraitisrnd3 Δες μήπως το κλείσεις και αυτό

**Comment by ChrisMoraitisrnd3** [comment]
@outcast1000 εμένα δουλεύει μια χαρά [public, fairy, 3.11]
