### ISSUE TITLE
Mini Maic/ Επιλογή προσωπικότητας (v3.09)

### ISSUE THREAD

**Issue by mariamls** [ChrisMoraitisrnd3/MAIC-Issues#38]
Μini Maic
Ρυθμίσεις συστήματος/ Επιλογή προσωπικότητας (απο γυναίκα /άνδρας)
Επανεκκίνηση της Maic

**Comment by outcast1000** [comment]
Εννοείς ότι έγινε επανεκκίνηση της MAIC μετά την αλλαγή? Μήπως πήρε κανα update? @ChrisMoraitisrnd3 ?

**Comment by ChrisMoraitisrnd3** [comment]
εάν είχε ήδη την 3.09 δεν πήρε update αλλιώς είναι αυτό που λέτε με τη μνήμη.

**Comment by mariamls** [comment]
@outcast1000 @ChrisMoraitisrnd3   Είχε ήδη την (v3.09) Δεν πήρε κάποιο update

**Comment by outcast1000** [comment]
Duplicate of #32 .Ας κλείσει

**Comment by outcast1000** [comment]
@ChrisMoraitisrnd3 ?
