### ISSUE TITLE
Mini Maic /ASR (v3.09)

### ISSUE THREAD

**Issue by mariamls** [ChrisMoraitisrnd3/MAIC-Issues#39]
1. Το asr κρατάει 2 με 3 λέξεις απο ολόκληρη πρόταση. 
2. Σε αρκετές περιπτώσεις ανοίγει και κλείνει χωρίς να καταχωρήσει τίποτα.
3. Πιο σπάνια άνοιξε και πριν μιλήσω έφερε την προηγούμενη ερώτηση και αμέσως μετά έβγαλε μήνυμα αδυναμία σύνδεσης στο δίκτυο. ( την ίδια ώρα η μεγάλη maic  έπαιζε κανονικά)

**Comment by ChrisMoraitisrnd3** [comment]
Πραγματικά δε ξέρω τι παίζει τον όροφό σας, και στην Ελενόρα είχε κάποια θεματάκια με την μικρή. 
@outcast1000  δε ξέρω αλλά σε μένα παίζει το ίδιο και ακούει το ίδιο με τις; μεγάλες που έχω. πρέπει να τσεκάρουμ πάλι το ιντερνετ κάτω? 
@mariamls μπορείς να φέρεις σε 5 λεπτά πάνω την μικρή που έχεις να την δοκιμάσεις στο δικό μου access point?

**Comment by outcast1000** [comment]
@ChrisMoraitisrnd3 Εχουμε τις κάρτες? Το Access point?

**Comment by ChrisMoraitisrnd3** [comment]
@outcast1000 @mariamls  Λοιπόν, ήρθε η Μαρία , συνδέθηκε στο Central στο access του ορόφου μας και δούλευει μια χαρά (μη πω καλύτερα από τη μεγάλη)
Πήρα το router με τη sim και δοκιμάζω εδώ στο γραφείο μου-> όλα καλά
Πάμε κάτω στο γραφείο της Μαρίας -> όλα μια χαρά
Κλείνω ρούτερ και συνδέω στο Central-->>> σέρνεταιιιιιι
Αποσυνδέω 5 συσκευές που υπάρχουν γύρω από τη Μαρία-> παίζει κανονικά

@outcast1000 πρέπει επειγόντως να δούμε το δίκτυο κάτω ή δε ξέρω τι άλλο παίζει
@mariamls  μπορείς να προσθέσεις άλλες παρατηρήσεις ή εάν ξέχασα τπτ

**Comment by outcast1000** [comment]
Για το δίκτυο τα έχουμε πει. Υπάρχει κάποιο άλλο θέμα σχετικό με προβλήματα στο sw? (Ας το κλείσουμε)

**Comment by ChrisMoraitisrnd3** [comment]
οκ εδώ σε μένα και από sim router
