### ISSUE TITLE
POIs Details - Back Button

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#4]
When you touch anywhere on screen ,you go back.
BUT you have the back button.

Pls, activate only back button

**Comment by outcast1000** [comment]
@ChrisMoraitisrnd3 γιατί έβαλες το "invalid" label?

**Comment by ChrisMoraitisrnd3** [comment]
> 
> 
> @ChrisMoraitisrnd3 γιατί έβαλες το "invalid" label?

this doesn't seem right!

**Comment by ChrisMoraitisrnd3** [comment]
still remain on v3.03

**Comment by gvergidis** [comment]
Το έκανα. Αν ο Jim πάρει τις αλλαγές μου πριν βγάλει έκδοση (Box) θα είναι και αυτό μεσα.

**Comment by gvergidis** [comment]
Jim received my collab and accepted box changes. This issue must have been fixed in this version. Make sure to check.

**Comment by ChrisMoraitisrnd3** [comment]
ok v3.05
