### ISSUE TITLE
Night mode - morning auto restart

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#40]
Σε περίπτωση που έχουμε ορίσει night mode μετά το restart δεν παραμένει.
Οπότε είναι μέχρι τις 5 και όχι μέχρι 7 το πρωί

**Comment by outcast1000** [comment]
@jimarab επιβεβαιώνεις;

**Comment by jimarab** [comment]
Αυτό φτιάχτηκε απότι φένεται

**Comment by outcast1000** [comment]
@ChrisMoraitisrnd3 Θα το κλείσουμε?

**Comment by ChrisMoraitisrnd3** [comment]
Στην 3.10 δε μπορούσα να καταλάβω πιο ακριβώς ήταν το Bug που βρήκε η Άννα.
Θέλω περισσότερη βοήθεια σε αυτό για να το δούμε σήμερα και να κλείσει

**Comment by ChrisMoraitisrnd3** [comment]
ok 3.11
