### ISSUE TITLE
Quotes & News / same every time

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#43]
Στα ρουμάνικα και πορτογαλικά ενώ είχε παραπάνω από 5 quotes έβγαζε μόνο και πάντα το ίδιο

**Comment by outcast1000** [comment]
@jimarab ?

**Comment by jimarab** [comment]
Θα το εξετάσω

**Comment by outcast1000** [comment]
@jimarab  Πες αν είναι πρόβλημα ή συμβαίνει κάτι άλλο για να το βάλω στο Jira

**Comment by ChrisMoraitisrnd3** [comment]
Με ενημέρωσαν οι γλωσσολόγοι όλα οκ
