### ISSUE TITLE
Size of backgrounds / POIs - Reminders

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#45]
Πρέπει να κάνουμε κάτι με τις διαστάσεις των παραθύρων που εμφανίζονται.
Πολλές φορές βλέπω πως υπάρχουν κενά στις αναδυόμενες καρτέλες πχ Υπενθυμίσεις, POIs

**Comment by ChrisMoraitisrnd3** [comment]
Έλεγχος της τοποθέτησης κάμερας για 2d και 3d (το είδαμε με τον Jim)

**Comment by outcast1000** [comment]
Πως πάει αυτό?

**Comment by ChrisMoraitisrnd3** [comment]
Στα POIs όταν έμπαινα στο κατάστημα, αντί για ορθογώνια ήταν πλάγια η προβολή της καρτέλας - παραμορφονώτανε κάτω από το μικρόφωνο- έκανε σκαλοπάτια. τώρα φαίνεται σωστά (3,13)
