### ISSUE TITLE
Διαδοχικό παίξιμο σταθμών

### ISSUE THREAD

**Issue by outcast1000** [ChrisMoraitisrnd3/MAIC-Issues#46]
"Παίξε Μελωδία FM" --> Παίζει. 
Ενώ είσαι μέσα και ακούς λές "Πάιξε Velvet FM. " Μένει στο Pause

**Comment by ChrisMoraitisrnd3** [comment]
Δείχνει ότι παίζει (εμφανίζει το pause) αλλά πρέπει να πατήσω το pause και ξανα Play για να παίξει

**Comment by gvergidis** [comment]
Διορθώθηκε. Θα περαστεί στην νέα έκδοση.

**Comment by ChrisMoraitisrnd3** [comment]
3.15 - > δεν λύθηκε το θέμα

**Comment by gvergidis** [comment]
Από το revert χάθηκε και ξέχασα να το περάσω. Είναι οκ ξανά.

**Comment by ChrisMoraitisrnd3** [comment]
"Παίξε Μελωδία Fm" δε παίζει με την πρώτη, προσπαθεί να κάνει streaming, 3 φορές ολοκληρώνεται ο κύκλος και μετά χάνεται το κουμπί. Τότε πρέπει να πατήσω το pause και να ξαναφορτώσει για να παίξει.
Βέβαια δε γίνεται όλες τις φορές- κάποιες παίζει με την πρώτη όπως και πολλοί άλλοι σταθμοί πχ zoo radio.
Θα ήθελα να ξαναδούμε @gvergidis  γιατί συμβαίνει αυτό και από τι προέρχεται.
Για αυτή την έκδοση στο radio δεν έχω να προσθέσω κάτι- όλα καλά.

**Comment by gvergidis** [comment]
Είναι το stream του σταθμού @ChrisMoraitisrnd3. Αν αργήσει να παίξει, δοκιμάζει ξανά και αν αποτύχει αλλάζει σταθμό. Αν θέλετε, μπορούμε να αυξήσουμε τον χρόνο προσπάθειας stream των σταθμών. Δεν είναι από εμάς. Γι αυτό και δεν θα το παρατηρήσεις σε όλους τους σταθμούς αλλά σε συγκεκριμένους.

**Comment by ChrisMoraitisrnd3** [comment]
@outcast1000  να το κάνει ο Γιώργος?

**Comment by gvergidis** [comment]
Αυτή τη στιγμή, είναι ρυθμισμένο να προσπαθεί το max 15 δευτερόλεπτα ή 3 φορές ανά σταθμό.
![RadioSettings](https://user-images.githubusercontent.com/9468098/58166120-ce044800-7c91-11e9-804d-13f3b0bbc6e1.jpg)

**Comment by ChrisMoraitisrnd3** [comment]
Ίσως μπορούμε κι άλλο να το βελτιώσουμε γιατί τώρα παίζει ένας σταθμός, asr, ζητάς άλλον σταθμό, αλλάζει καρτέλα, παίζει λίγο από τον προηγούμενο σταθμό και φορτώνει τον δεύτερον.
Αλλά παίζει κανονικά μετά, κανένα πρόβλημα. Θα το κλείσω και το συζητάμε σε άλλο topic
