### ISSUE TITLE
Night mode / usage

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#51]
Παράδειγμα:
Εάν είναι 14:00 και επιλέξω αυτόματη λειτουργία , βάζω ώρα 13:50.
Θα πρέπει να ενεργοποιείται η νυχτερινή λειτουργία ή όχι?

**Comment by jimarab** [comment]
Καλησπέρα,
Όχι.

**Comment by mariamls** [comment]
Στη λειτουργία νύχτας/ ρυθμίσεις/ αυτόματη ενεργοποίηση/ επιλογή, εμφανίζεται ένα πινακάκι που δεν είναι ευανάγνωστο στο χρήστη.  Οι αριθμοί βγαίνουν πάνω στα γραμματα.

**Comment by ChrisMoraitisrnd3** [comment]
Μαρία το έχω γράψει και είναι αλλού. Επίσης, εδώ έχει καρτέλα discussion και όχι Bug. Το μεταφέρω

**Comment by gvergidis** [comment]
Διορθώθηκε. Είχα ξεχάσει να περάσω το κλειδί στις μεταφράσεις. Όλα οκ.
