### ISSUE TITLE
Radio / Next

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#52]
Παίζει το πρώτο και τα υπόλοιπα κολλάνε (στο next)
Προσοχή στο βινύλιο- γυρίζει πιο γρήγορα- υπενθύμιση @gvergidis

**Comment by mariamls** [comment]
Συμβαίνει και στους αγαπημένους σταθμούς να μην παίζει τα επόμενα και κάποιες φορές στην προσπάθεια να παίξει επέστρεψε στον προηγούμενο.

**Comment by outcast1000** [comment]
Αρα @gvergidis .
1. Εβγαλες τα trim
2. Αλλαξες το plugin.
3. Εκανες κάποιο restart τον player 

Τελικά βγήκε Bbug. Τι από αυτά φταίει?

**Comment by gvergidis** [comment]
Πραγματικά δεν έχω ιδέα. Τα έκανα revert και πάλι δεν δούλεψε. Σήμερα που μπόρεσα, διάβασα το manual και χρησιμοποιώ έναν manager που χειρίζεται την αναπαραγωγή από μόνος του. Φαίνεται να δουλεύει σωστά. Θα βγουν κάποια μικρά bugs αλλά σημασία έχει πως το playback είναι σωστό. Το καλό είναι πως πλέον παίζουν περισσότεροι σταθμοί από πριν.

**Comment by gvergidis** [comment]
Διορθώθηκε το πρόβλημα. Έκανα μια αλλαγή και φαίνεται να δουλεύει καλύτερα από πριν. Το είχα διορθώσει όντως από νωρίς αλλά είχε κολλήσει το Unity. Έκανα ένα restart και δούλεψαν όλα τέλεια. @ChrisMoraitisrnd3 θα υπάρχουν κάποια μικρά bugs στο UI . Δεν μπήκα στη διαδικασία να τα φτιάξω τώρα γιατί βιαζόμαστε για έκδοση.

**Comment by ChrisMoraitisrnd3** [comment]
οκ v3.15
