### ISSUE TITLE
Reminders (v.3.13)

### ISSUE THREAD

**Issue by mariamls** [ChrisMoraitisrnd3/MAIC-Issues#53]
Μόλις ορίσεις μια υπενθύμιση, εμφανίζεται η λίστα των υπενθυμίσεων χωρίς να σου λέει 'εντάξει το προγραμμάτησα' όπως κάνει στα ξυπνητήρια για παράδειγμα.

**Comment by ChrisMoraitisrnd3** [comment]
ok 3.15 (αν και εμένα έλεγε στη προηγούμενη)
