### ISSUE TITLE
Youtube / λίστες

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#57]
"Θέλω ξένη μουσική"...."Disco" και παίζει συνέχεια το πρώτο της λίστας.
Δε ξέρω εάν ήταν τυχαίο αλλά το δεύτερο κομμάτι δεν υπήρχε, πήγε στο τρίτο και κόλλησε εκεί (συνέχεια buffering) πατάω επόμενο και παίζει πάλι το πρώτο αλλά οι τίτλοι από κάτω αλλάζουν ενώ το βίντεο παραμένει το ίδιο.
Ζητάω πάλι το ίδιο, μου βγάζει premium λίστα, και ότι να ναι βίντεο και παίζει το ίδιο για όλη τη λίστα!?!

**Comment by ChrisMoraitisrnd3** [comment]
Μετά έχει σκάσει και παίζει ότι να ναι και πολλές φορές δε παίζει τίποτα.
Η άλλη συσκευή παίζει κανονικά. Το πρόβλημα για μένα δημιουργήθηκε τη στιγμή που δε βρέθηκε το τραγούδι στη λίστα.

**Comment by mariamls** [comment]
@ChrisMoraitisrnd3  το τραγούδι που λές ότι πάιζει συνέχεια, ακούγεται και σε άλλες λίστες όχι μόνο στη disco! Ακόμα και στην κλασική μουσική. Και σε ελληνικές λίστες ( you make me feel mighty real). Ακόμα και στον Αντώνη Ρέμο....

**Comment by mariamls** [comment]
Κρατάει το τελευταίο τραγούδι που έχει παίξει, οπότε και στον Αντώνη Ρέμο βγάζει αυτό το κομμάτι. Οι τίτλοι των τραγουδιών δεν έχουν καμία σχέση. Public/ Dev συμβαίνει αυτό.

**Comment by gvergidis** [comment]
Διορθώθηκε. Για κάποιο λόγο έβρισκε ένα null και συνεπώς κράσαρε ο resolver άρα το βίντεο έμενε πάντα ίδιο. Θα περαστεί η αλλαγή σ αυτή την έκδοση.

**Comment by ChrisMoraitisrnd3** [comment]
ok v3.17
