### ISSUE TITLE
Youtube - TTS says all video titles

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#7]
Ask for travel- tips.
Maic is reading the rest of the titles' videos

**20190424_content-travel**

[\\192.168.0.70\Public\For_GitHub](url)

**Comment by outcast1000** [comment]
It is possible that Youtube fails to play every video

**Comment by gvergidis** [comment]
Το είδαμε και εμείς σε μία συσκευή αλλά δεν ήταν πρόβλημα του engine. Το βίντεο έπαιξε κανονικά και δεν έφταιξε το ότι πχ απέτυχε το decryption και άρα προχωρούσα κάθε φορά σε επόμενο βίντεο. Θα κοιτάξουμε περισσότερο.

**Comment by ChrisMoraitisrnd3** [comment]
ok v3.11 - wifi πρόβλημα
