### ISSUE TITLE
Radio - No thumbnail for stations

### ISSUE THREAD

**Issue by ChrisMoraitisrnd3** [ChrisMoraitisrnd3/MAIC-Issues#8]
When you ask for your favorite radio stations, the stations do not have 
![20190424_favour-radio](https://user-images.githubusercontent.com/49868121/56648093-54297080-668b-11e9-869f-01f7ba555b2b.jpg)
image

**Comment by gvergidis** [comment]
Υπήρχε ένα πρόβλημα κατά το deserialize. Λογικά οφείλεται εκεί καθώς crashαρε το script. Διορθώθηκε. Ας δοκιμαστεί εκ νέου.

**Comment by ChrisMoraitisrnd3** [comment]
Με το που προσθέσω σταθμό στα αγαπημένα, όταν ξαναζητήσω να παίξει αγαπημένα τώρα βγάζει τη default εικόνα (ο σταθμός είχε εικόνα πριν)

**Comment by gvergidis** [comment]
Η λογική είναι πως οι σταθμοί που δεν έχουν εικόνα, κάθε φορά που τους βάζει ο χρήστης να παίξουν, ο controller προσπαθεί να κατεβάσει την εικόνα ξανά. Όταν αποτυγχάνει, χρησιμοποιείται η default εικόνα για τον σταθμό. Δεν είναι bug.

**Comment by outcast1000** [comment]
@gvergidis  Το σενάριο αναπαραγωγής (αν κάνω λάθος @ChrisMoraitisrnd3  πές μου) είναι:
1. Βλέπεις ένα σταθμό - έχει thumbnail
2. Το βάζεις στα αγαπημένα - έχει thumbnail
3. Τον επιλέγεις από τα αγαπημένα για να "τον παίξεις"- ΔΕΝ έχει thumnail
